/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'FTL.amd64'
*/
#include <vector>
#include <string>
#include <utility>
#include <map>
#include <queue>

struct GL_Primitive;
struct Door;
struct CrewAnimation;
struct ShipSystem;
struct Repairable;
struct GL_Texture;

/* 315 */
struct GL_Color
{
  float r;
  float g;
  float b;
  float a;
};



/* 304 */
struct __attribute__((aligned(8))) ShipObject
{
  void ** vptr;
  int iShipId;
  //char pad0[4]; 
};

/* 1464 */
struct __attribute__((aligned(8))) CrewTarget : ShipObject
{
};

/* 520 */
struct Point
{
  int x;
  int y;
};



/* 2978 */
struct __attribute__((aligned(8))) Path
{
  Point start;
  std::vector<Door*> doors;
  Point finish;
  float distance;
  //char pad0[4];
};

/* 1391 */
struct Slot
{
  int roomId;
  int slotId;
  Point worldLocation;

};

/* 1240 */
struct CachedPrimitive
{
  void ** vptr;
  GL_Primitive *primitive;
};

struct __attribute__((aligned(4))) CachedImage : CachedPrimitive
{
  std::string imageName;
  GL_Texture *texture;
  int x;
  int y;
  float wScale;
  float hScale;
  float x_start;
  float y_start;
  float x_size;
  float y_size;
  float rotation;
  bool mirrored;
  //char pad0[3];
};

/* 1475 */
struct CachedRect : CachedPrimitive
{
  int x;
  int y;
  int w;
  int h;
};

/* 1241 */
struct AnimationTracker
{
  void **vptr;
  float time;
  bool loop;
  //char pad0[3];
  float current_time;
  bool running;
  bool reverse;
  bool done;
  //char pad1[1];
  float loopDelay;
  float currentDelay;
};

/* 373 */
struct  Pointf
{
  float x;
  float y;
};

/* 7235 */
struct  BoardingGoal
{
  float fHealthLimit;
  int causedDamage;
  int targetsDestroyed;
  int target;
  int damageType;
};

/* 886 */
struct  CrewTask
{
  int taskId;
  int room;
  int _sil__DO_NOT_USE_system;
};

/* 2439 */
typedef std::string string;

/* 2491 */
struct  __attribute__((aligned(8))) TextString
{
  string data;
  bool isLiteral;
  //char pad0[7];
};

/* 1309 */
struct  Description
{
  TextString title;
  TextString shortTitle;
  TextString description;
  int cost;
  int rarity;
  int baseRarity;
  int bp;
  bool locked;
  //char pad0[7];
  TextString tooltip;
  string tip;
};

/* 306 */
struct __attribute__((aligned(8))) Blueprint
{
  void **vptr;
  string name;
  Description desc;
  int type;
  //char pad0[4];
};



/* 307 */
struct CrewBlueprint : Blueprint
{
  TextString crewName;
  TextString crewNameLong;
  std::vector<TextString> powers;
  bool male;
  //char pad0[7];
  std::vector<std::pair<int,int>> skillLevel;
  std::vector<std::vector<GL_Color>> colorLayers;
  std::vector<int> colorChoices;
};

/* 2471 */
struct AnimationDescriptor
{
  int numFrames;
  int imageWidth;
  int imageHeight;
  int stripStartY;
  int stripStartX;
  int frameWidth;
  int frameHeight;
};


/* 630 */
struct Animation
{
  GL_Texture *animationStrip;
  AnimationDescriptor info;
  //char pad0[4];
  AnimationTracker tracker;
  Pointf position;
  std::string soundForward;
  std::string soundReverse;
  bool randomizeFrames;
  //char pad1[3];
  float fScale;
  float fYStretch;
  int currentFrame;
  bool bAlwaysMirror;
  //char pad2[7];
  std::vector<std::vector<std::string>> soundQueue;
  float fadeOut;
  float startFadeOut;
  string animName;
  int mask_x_pos;
  int mask_x_size;
  int mask_y_pos;
  int mask_y_size;
  GL_Primitive *primitive;
  GL_Primitive *mirroredPrimitive;
};

/* 4447 */
struct __attribute__((aligned(8))) SCrewStats
{
  std::vector<int> stat;
  string species;
  string name;
  bool male;
  //char pad0[7];
};

struct DoorState {
  int32_t state;
  bool hacked;
  int level;
};

struct Projectile;
struct WeaponMount;
struct WeaponAnimation;
struct CrewBlueprint;
struct GL_Primitive;
struct Pointf;
struct OuterHull;
struct Room;
struct Door;
struct ShipSystem;
struct DamageMessage;
struct CrewMember;
struct Drone;
struct Animation;
struct CloneSystem;
struct ArtillerySystem;
struct SpaceDrone;
struct WeaponSystem;
struct HackingSystem;
struct BatterySystem;
struct TeleportSystem;
struct MindSystem;
struct ParticleEmitter;
struct CloakingSystem;
struct DroneSystem;
struct GL_Texture;
struct MedbaySystem;
struct EngineSystem;
struct LockdownShard;
struct Shields;
struct OxygenSystem;
struct Fire;

struct  ImageDesc
{
  GL_Texture *tex;
  int resId;
  int w;
  int h;
  int x;
  int y;
  int rot;
};

struct  ExplosionAnimation : AnimationTracker, ShipObject
{
  std::vector<Animation> explosions;
  std::vector<GL_Texture*> pieces;
  std::vector<std::string> pieceNames;
  std::vector<float> rotationSpeed;
  std::vector<float> rotation;
  std::vector<std::pair<float,float>> rotationSpeedMinMax;
  std::vector<Pointf> movementVector;
  std::vector<Pointf> position;
  std::vector<Pointf> startingPosition;
  float explosionTimer;
  float soundTimer;
  bool bFinalBoom;
  bool bJumpOut;
  std::vector<WeaponAnimation*> weaponAnims;
  Point pos;
};

struct Globals {
  struct Ellipse;
};

/* 2563 */
struct  Globals::Ellipse
{
  Point center;
  float a;
  float b;
};


/* 4293 */
struct  Ship : ShipObject
{
  std::vector<Room*> vRoomList;
  std::vector<Door*> vDoorList;
  std::vector<OuterHull*> vOuterWalls;
  std::vector<Door*> vOuterAirlocks;
  std::pair<int,int> hullIntegrity;
  std::vector<WeaponMount> weaponMounts;
  std::string floorImageName;
  ImageDesc shipFloor;
  GL_Primitive *floorPrimitive;
  std::string shipImageName;
  ImageDesc shipImage;
  Point glowOffset;
  GL_Primitive *shipImagePrimitive;
  std::string cloakImageName;
  ImageDesc shipImageCloak;
  GL_Primitive *cloakPrimitive;
  GL_Primitive *gridPrimitive;
  GL_Primitive *wallsPrimitive;
  GL_Primitive *doorsPrimitive;
  std::vector<DoorState> doorState;
  bool lastDoorControlMode;
  GL_Texture *thrustersImage;
  GL_Texture *jumpGlare;
  int vertical_shift;
  int horizontal_shift;
  std::string shipName;
  ExplosionAnimation explosion;
  bool bDestroyed;
  Globals::Ellipse baseEllipse;
  Animation engineAnim[2];
  AnimationTracker cloakingTracker;
  bool bCloaked;
  bool bExperiment;
  bool bShowEngines;
  std::vector<LockdownShard> lockdowns;
};

/* 611 */
struct CrewMember 
{
  char pad0[0x0c];
  float x;
  float y;
  float size;
  float scale;
  float goal_x;
  float goal_y;
  int width;
  int height;
  std::pair<float,float> health;
  float speed_x;
  float speed_y;
  Path path;
  bool new_path;
  float x_destination;
  float y_destination;
  Door *last_door;
  Repairable *currentRepair;
  bool bSuffocating;
  int moveGoal;
  int selectionState;
  int iRoomId;
  int iManningId;
  int iRepairId;
  int iStackId;
  Slot currentSlot;
  bool intruder;
  bool bFighting;
  bool bSharedSpot;
  CrewAnimation *crewAnim;
  GL_Texture *selectionImage;
  CachedImage healthBox;
  CachedImage healthBoxRed;
  CachedRect healthBar;
  float fMedbay;
  float lastDamageTimer;
  float lastHealthChange;
  int currentShipId;
  AnimationTracker flashHealthTracker;
  Pointf currentTarget;
  CrewTarget *crewTarget;
  BoardingGoal boardingGoal;
  bool bFrozen;
  bool bFrozenLocation;
  //char pad5[2];
  CrewTask task;
  //char pad6[4];
  string type;
  Ship *ship;
  Slot finalGoal;
  Door *blockingDoor;
  bool bOutOfGame;
  //char pad7[7];
  string species;
  bool bDead;
  //char pad8[3];
  int iOnFire;
  bool bActiveManning;
  //char pad9[7];
  ShipSystem *currentSystem;
  int usingSkill;
  //char pad10[4];
  CrewBlueprint blueprint;
  Animation healing;
  Animation stunned;
  AnimationTracker levelUp;
  int lastLevelUp;
  //char pad11[4];
  SCrewStats stats;
  std::vector<std::vector<bool>> skillsEarned;
  bool clone_ready;
  bool bMindControlled;
  int iDeathNumber;
  Animation mindControlled;
  Animation stunIcon;
  std::vector<std::vector<AnimationTracker>> skillUp;
  int healthBoost;
  float fMindDamageBoost;
  float fCloneDying;
  bool bResisted;
  //char pad12[3];
  Slot savedPosition;
  float fStunTime;
  //char pad13[4];
  CachedImage movementTarget;
  bool bCloned;
  //char pad14[7];
  Point GetPosition() {
    {
        using Fn = Point(*)(CrewMember*);
        return reinterpret_cast<Fn>(0x43BE10)(this);
    }
  }
};


/* 1368 */
struct  __attribute__((aligned(4))) Targetable
{
  void **vptr;
  int type;
  bool hostile;
  bool targeted;
};

/* 1367 */
struct  Collideable
{
  void **vptr;
};

/* 1366 */
template<typename T>
struct  Spreader : ShipObject
{
  int count;
  std::vector<int> roomCount;
  std::vector<std::vector<T>> grid;
};


/* 353 */
struct ShipBlueprint_SystemTemplate
{
  int systemId;
  int powerLevel;
  std::vector<int> location;
  int bp;
  int maxPower;
  string image;
  int slot;
  int direction;
  std::vector<std::string> weapon;
};


/* 959 */
struct  ShipBlueprint : Blueprint
{
  Description desc;
  string blueprintName;
  TextString name;
  TextString shipClass;
  string layoutFile;
  string imgFile;
  string cloakFile;
  string shieldFile;
  string floorFile;
  std::map<int,ShipBlueprint_SystemTemplate> systemInfo;
  std::vector<int> systems;
  int droneCount;
  int originalDroneCount;
  int droneSlots;
  string loadDrones;
  std::vector<std::string> drones;
  std::vector<std::string> augments;
  int weaponCount;
  int originalWeaponCount;
  int weaponSlots;
  string loadWeapons;
  std::vector<std::string> weapons;
  int missiles;
  int drone_count;
  int health;
  int originalCrewCount;
  std::vector<std::string> defaultCrew;
  std::vector<CrewBlueprint> customCrew;
  int maxPower;
  int boardingAI;
  int bp_count;
  int maxCrew;
  int maxSector;
  int minSector;
  TextString unlock;
};

/* 1460 */
struct __attribute__((aligned(8))) Selectable
{
  void **vptr;
  int selectedState;
};

/* 658 */
struct Repairable : Selectable, ShipObject
{
  float fDamage;
  Point pLoc;
  float fMaxDamage;
  std::string name;
  int roomId;
  int iRepairCount;
};

/* 1463 */
struct Spreadable : Repairable
{
  std::string soundName;
};

/* 643 */
struct __attribute__((aligned(8))) Fire : Spreadable
{
  float fDeathTimer;
  float fStartTimer;
  float fOxygen;
  Animation fireAnimation;
  Animation smokeAnimation;
  bool bWasOnFire;
};



/* 661 */
struct  __attribute__((aligned(8))) ShipManager : ShipObject, Targetable, Collideable
{
  std::vector<ShipSystem*> vSystemList;
  OxygenSystem *oxygenSystem;
  TeleportSystem *teleportSystem;
  CloakingSystem *cloakSystem;
  BatterySystem *batterySystem;
  MindSystem *mindSystem;
  CloneSystem *cloneSystem;
  HackingSystem *hackingSystem;
  bool showNetwork;
  bool addedSystem;
  Shields *shieldSystem;
  WeaponSystem *weaponSystem;
  DroneSystem *droneSystem;
  EngineSystem *engineSystem;
  MedbaySystem *medbaySystem;
  std::vector<ArtillerySystem*> artillerySystems;
  std::vector<CrewMember*> vCrewList;
  Spreader<Fire> fireSpreader;
  Ship ship;
  std::queue<std::string> statusMessages;
  bool bGameOver;
  ShipManager *current_target;
  std::pair<float,float> jump_timer;
  int fuel_count;
  bool hostile_ship;
  bool bDestroyed;
  int iLastDamage;
  AnimationTracker jumpAnimation;
  std::vector<DamageMessage*> damMessages;
  std::vector<int> systemKey;
  int currentScrap;
  bool bJumping;
  bool bAutomated;
  int shipLevel;
  ShipBlueprint myBlueprint;
  bool lastEngineStatus;
  bool lastJumpReady;
  bool bContainsPlayerCrew;
  int iIntruderCount;
  std::vector<std::vector<int>> crewCounts;
  int tempDroneCount;
  int tempMissileCount;
  std::vector<Animation> explosions;
  std::vector<bool> tempVision;
  bool bHighlightCrew;
  std::vector<Drone*> droneTrash;
  std::vector<SpaceDrone*> spaceDrones;
  std::vector<SpaceDrone*> newDroneArrivals;
  int bpCount;
  int iCustomizeMode;
  bool bShowRoom;
  std::vector<Projectile*> superBarrage;
  bool bInvincible;
  std::vector<SpaceDrone*> superDrones;
  GL_Primitive *highlight;
  int failedDodgeCounter;
  std::vector<float> hitByBeam;
  bool enemyDamagedUncloaked;
  int damageCloaked;
  std::map<int,int> killedByBeam;
  int minBeaconHealth;
  std::vector<ParticleEmitter*> fireExtinguishers;
  bool bWasSafe;
};


struct CrewBlueprint;


